version: '3.8'
networks:
  example:
    driver: bridge
services:
  data_service:
    container_name: 'data_service'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8181:8181'
    networks:
      - example
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=jdbc:postgresql://localhost/filmrate'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - example
